### ISSUE TITLE
"Terminal" config option (replace bestiary entry) disables all keywords for "The Company Building" (moon) on game V.50

### ISSUE THREAD

**Issue by BMaroon** [Wolfmyths/LC-MikuBraken#2]
As stated, when the option to replace the bestiary option is enabled, the keywords for the company building are disabled.
Easy fix in the short-term is to disable the option by default. 
Unsure what the actual conflict is at the moment. But the mod otherwise works with the bestiary entry option disabled.

**Comment by Wolfmyths** [comment]
From first glance, what seems to be happening is that the mod is overriding a specific position in a list of keywords (In this case 36). And the new update shifted those items around overriding the company building instead of the braken

I'll look into it

**Comment by Wolfmyths** [comment]
The bug has been fixed and there shouldn't be anymore issues like this in the future unless the dev decides to change the name of the keyword or bestiary name

A patch will be out shortly thanks for reporting!
